// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oojhhvutzzkvugizucks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vamhodnV0enprdnVnaXp1Y2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDE4ODMsImV4cCI6MjA2MTExNzg4M30.iTXRG1BXEk3qgURRH9Z6HLtXJtPgSxBFBqFmUYWBV64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);