// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faokyoqyndcbotxkggyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhb2t5b3F5bmRjYm90eGtnZ3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mjg0MzUsImV4cCI6MjA2MTAwNDQzNX0.P1hGJMIICip4VMStszOxi0NHHHioCld8JPN4L2JK9S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);